name: ""
navbar: 
  left: 
    - href: index.html
      text: Home
  title: ""
output_dir: docs
output:
  html_document:
    lib_dir: site_libs
    self_contained: no
    theme: lumen
    highlight: tango
    smooth_scroll: false
    df_print: paged
    include:
      after_body: footer.html
